name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
  release-npm:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        # Setup .npmrc file to publish to npm
        - uses: actions/setup-node@v3
          with:
            registry-url: 'https://registry.npmjs.org'
        - name: Install Deps
          run: yarn install
        - name: Build
          run: yarn build
        - name: Release
          run: cd dist/bundle && yarn publish --access public --non-interactive
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
